import React,{useEffect,useMemo,useRef,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';import{db,configured}from'./lib/db.js';
const B=[['Founders Tower','Landmark',25000,42000,230,48,18,'#ff405c'],['Apex House','Tower',12000,18600,180,28,34,'#13d4a3'],['Studio 88','Mid-Rise',3500,5100,115,67,42,'#8d5cff'],['Commerce One','Tower',9000,12750,160,52,58,'#ffad32'],['Pixel House','Boutique',850,1200,80,20,61,'#26a7ff'],['North Point','Mid-Rise',2800,3300,105,78,24,'#f04cd4']].map((x,i)=>({id:i,name:x[0],tier:x[1],price:x[2],wealth:x[3],h:x[4],x:x[5],y:x[6],c:x[7]}));
function Building({b,onPick}){const h=Math.max(76,Math.min(220,Number(b.h)||100)),w=b.tier==='Landmark'?112:b.tier==='Tower'?92:76;return <button className="building" onClick={e=>{e.stopPropagation();onPick(b)}} style={{left:b.x+'%',top:b.y+'%',width:w,height:h,'--c':b.c,'--side':'color-mix(in srgb,'+b.c+' 62%,#05070a)'}} aria-label={b.name}><i className="roof"/><i className="face front"/><i className="face side"/><i className="windows"/><span>{b.name}</span></button>}
function App(){const[items,setItems]=useState(B),[s,setS]=useState(B[0]),[q,setQ]=useState(''),[zoom,setZoom]=useState(.92),[pos,setPos]=useState({x:-80,y:-20});const drag=useRef(null);
useEffect(()=>{if(configured)db.properties().then(rows=>{if(rows?.length){const m=rows.map(x=>({...x,price:Number(x.base_value),wealth:Number(x.asset_wealth),h:x.height,c:x.color}));setItems(m);setS(m[0])}}).catch(()=>{})},[]);
const shown=useMemo(()=>items.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())),[items,q]);
const down=e=>{drag.current={x:e.clientX,y:e.clientY,ox:pos.x,oy:pos.y};e.currentTarget.setPointerCapture(e.pointerId)};const move=e=>{if(drag.current)setPos({x:drag.current.ox+e.clientX-drag.current.x,y:drag.current.oy+e.clientY-drag.current.y})};const up=()=>drag.current=null;
return <main><header><b className="logo">SPOTS</b><nav>WORLD　PROPERTIES　RANKINGS</nav><input className="search" placeholder="Search the city" value={q} onChange={e=>setQ(e.target.value)}/></header>
<section className="world"><div className="hud"><div><small>SPOTS WORLD</small><h1>Explore the city.</h1></div><div className="stats"><b>{items.length}</b><span>PROPERTIES</span></div></div>
<div className="viewport" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onWheel={e=>setZoom(z=>Math.max(.55,Math.min(1.65,z-e.deltaY*.001)))}><div className="scene" style={{transform:'translate('+pos.x+'px,'+pos.y+'px) scale('+zoom+')'}}><div className="ground"/><div className="road r1"/><div className="road r2"/><div className="road r3"/><div className="plaza"><b>SPOTS</b><i/><i/><i/></div>{shown.map(b=><Building key={b.id} b={b} onPick={setS}/>)}{[1,2,3,4,5,6,7,8].map(n=><i key={n} className={'tree t'+n}/>)}</div></div>
<div className="controls"><button onClick={()=>setZoom(z=>Math.min(1.65,z+.15))}>＋</button><button onClick={()=>setZoom(z=>Math.max(.55,z-.15))}>−</button><button onClick={()=>{setZoom(.92);setPos({x:-80,y:-20})}}>⌂</button></div>
<aside className="property"><small>SELECTED PROPERTY</small><h2>{s.name}</h2><div className="badges"><b>{s.tier}</b><b>AVAILABLE</b></div><div className="money"><span>BASE VALUE<strong>$ {Number(s.price).toLocaleString()}</strong></span><span>SPOT ASSET WEALTH<strong>$ {Number(s.wealth).toLocaleString()}</strong></span></div><button>VIEW PROPERTY</button></aside>
<div className="hint">DRAG TO EXPLORE · SCROLL OR PINCH TO ZOOM</div></section>
<section className="below"><small>THE DIGITAL CITY OF OWNERSHIP</small><h2>Claim your place. Build your presence.</h2><p>Properties, identity and achievement come together in one living digital city.</p></section></main>}
createRoot(document.getElementById('root')).render(<App/>);