import React,{useEffect,useMemo,useRef,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';import{db,configured}from'./lib/db.js';
const FALLBACK=[['Founders Tower','Landmark',25000,42000,230,'#ff405c'],['Apex House','Tower',12000,18600,180,'#13d4a3'],['Studio 88','Mid-Rise',3500,5100,115,'#8d5cff'],['Commerce One','Tower',9000,12750,160,'#ffad32'],['Pixel House','Boutique',850,1200,80,'#26a7ff'],['North Point','Mid-Rise',2800,3300,105,'#f04cd4']].map((x,i)=>({id:i,name:x[0],tier:x[1],price:x[2],wealth:x[3],h:x[4],c:x[5],district:'Central'}));
function Building({b,i,onPick}){const h=Math.max(80,Math.min(250,Number(b.h||b.height)||110)),kind=b.tier==='Landmark'?'landmark':b.tier==='Tower'?'towerType':b.tier==='Boutique'?'boutique':'midrise';return <button className={'building '+kind} onClick={()=>onPick(b)} style={{'--c':b.c||b.color,'--h':h+'px','--delay':(i%5)*.15+'s'}}><i className="antenna"/><i className="crown"/><i className="roof"/><i className="face front"/><i className="face side"/><i className="windows"/><i className="awning"/><span>{b.name}</span></button>}
function App(){const[items,setItems]=useState(FALLBACK),[s,setS]=useState(FALLBACK[0]),[q,setQ]=useState('');const rail=useRef(null);
useEffect(()=>{if(configured)db.properties().then(rows=>{if(rows?.length){const m=rows.map(x=>({...x,price:Number(x.base_value),wealth:Number(x.asset_wealth),h:x.height,c:x.color}));setItems(m);setS(m[0])}}).catch(()=>{})},[]);
const shown=useMemo(()=>items.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())),[items,q]);
const nudge=d=>rail.current?.scrollBy({left:d,behavior:'smooth'});
return <main><header><b className="logo">SPOTS</b><nav>THE AVENUE　 PROPERTIES　 RANKINGS</nav><input className="search" placeholder="Search the avenue" value={q} onChange={e=>setQ(e.target.value)}/></header>
<section className="avenue"><div className="leftTools"><button>♕</button><button>⌕</button><button>◌</button><button>⌖</button><button>↪</button></div><div className="statsPill"><b>● {items.length}</b><i/> <b>◉ 142,631</b><span>Click to view stats</span></div><div className="zoomTools"><button>＋</button><button>−</button><button onClick={()=>nudge(-650)}>↑</button><button onClick={()=>nudge(650)}>↓</button></div>
<div className="rail" ref={rail}>{shown.map((b,i)=><section className="plot" key={b.id||b.name}><div className="skylabel">{b.district||'SPOTS'}</div><div className="backline"><i/><i/><i/></div><Building b={b} i={i} onPick={setS}/><div className="sidewalk">{Array.from({length:3},(_,p)=><i className={'walker w'+p} key={p}><b/></i>)}</div><div className="street"><i className={'car c'+(i%3)}/><em>SPOT {String(i+1).padStart(3,'0')}</em></div>{i%6===4&&<div className="miniPark"><i/><i/><b>SPOTS PARK</b></div>}</section>)}</div>
<button className="arrow left" onClick={()=>nudge(-650)}>‹</button><button className="arrow right" onClick={()=>nudge(650)}>›</button>
<div className="salesBar"><div><small>TOTAL SALES</small><b>$32,505</b></div><button>CLAIM A SPOT FROM $5</button><button className="viewAll">↗ VIEW ALL</button></div><div className="ticker"><b>● SPOTS WORLD</b> expanded the avenue · live city activity <strong>NOW</strong></div>
<aside className="property"><small>SELECTED PROPERTY</small><h2>{s.name}</h2><div className="badges"><b>{s.tier}</b><b>AVAILABLE</b></div><div className="money"><span>BASE VALUE<strong>$ {Number(s.price).toLocaleString()}</strong></span><span>SPOT ASSET WEALTH<strong>$ {Number(s.wealth).toLocaleString()}</strong></span></div><button>VIEW PROPERTY</button></aside></section><section className="rankings">{items.slice(0,3).map((x,i)=><article key={x.id||x.name}><b>{String(i+1).padStart(2,'0')}</b><span><strong>{x.name}</strong><small>{x.district||x.tier}</small></span><em>$ {Number(x.price).toLocaleString()}</em></article>)}</section>
<section className="below"><small>ONE CITY · ONE CONTINUOUS AVENUE</small><h2>Every property has a permanent place in Spots.</h2></section></main>}
createRoot(document.getElementById('root')).render(<App/>);